services:
  whisper-webui:
    image: dockermaker0/whisper-webui:1.0.9
    container_name: whisper-webui
    pull_policy: always
    restart: unless-stopped

    ports:
      - "7860:7860"

    volumes:
      - ./models:/Whisper-WebUI/models
      - ./outputs:/Whisper-WebUI/outputs
      - ./configs:/Whisper-WebUI/configs

    command:
      - --server_port
      - "7860"
      - --server_name
      - 0.0.0.0

    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:7860/ > /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
